# 수정 필요 
- 결정 세번 여러개인 경우 코드 수집 X
- 결정 세번 형식 다른 경우 통일 필요

### 필요 함수 호출

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By  
from selenium.webdriver.support.ui import Select  
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time
import os
import re

In [3]:
# 사이트 불러오기
driver = webdriver.Chrome(service = Service(), options = webdriver.ChromeOptions())  
driver.get('https://unipass.customs.go.kr/clip/index.do')

In [4]:
TIME = 3 
Ryu = 33

driver.find_element(By.ID, 'TOPMENU_LNK_M_ULS0200000000').click()  # HS CODE 버튼
time.sleep(TIME)

# 국내 품목 사례 버튼 
driver.find_element(By.ID, 'LEFTMENU_LNK_M_ULS0807030051').click() 
time.sleep(TIME)

# 33류 입력 
ele = driver.find_element(By.ID, 'srchDtrmHsSgn')
ele.send_keys(Ryu)
ele.send_keys(Keys.ENTER)
time.sleep(TIME)

In [75]:
# l = range(1,11)
# print(l[3])
# print(l)  # 헐 ,,, , , 객체로 리턴
# print(list(l))

4
range(1, 11)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
# l1 = '12.3 4.56 78.9 1.23 456 789'
# l2 = l1.split(' ')
# print(l2)
# n = len(l2)
# l2[1:n:2]
# l3 = [float(x) for x in str_list]
# l3.append((l2[1:n:2].apply(lambda x: re.sub(r'[^0-9]', '', x))))
# l3.append(l2[0])
# l3

['12.3', '4.56', '78.9', '1.23', '456', '789']

NameError: name 'str_list' is not defined

### 자료 수집

In [27]:
# 데이터 저장 형태 : 리스트? 딕셔너리? 
TIME = 5
date_list = []     # 시행 일자 
agency_list = []   # 시행 기관 
hs_code_list = []  # hs code  
product_list = []  # 품명 
pd_description_list = []   # 물품 설명 
hs_description_list = []   # 결정 사유
count = 0

while True:
    # 10페이지씩 사례 분석
    for i in range(1,11): 
        # 다음 페이지 클릭
        # 1 페이지 3번 //*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[3]/a 
        # 2 페이지 3번 //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[3]/a
        # 3 페이지 3번 //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[3]/a
        driver.find_element(By.XPATH, f'//*[@id="ULS0203042S_T3_container"]/div[2]/ul[{count + 1}]/li[{i}]').click()

        time.sleep(TIME)
                     
        for i in range(1,11):
            # 사례 클릭 
            driver.find_element(By.XPATH, f'//*[@id="ULS0203042S_T3_table1"]/tbody/tr[{i}]/td[4]/a').click()
            time.sleep(TIME)
            # HS CODE가 여러개일 경우 .. 처리할 방법 
                  
            # 사례 정보 수집
                  
            date_list.append(driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[2]/td').text)
            agency_list.append(driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[3]/td').text)
            hs_code = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[4]/td').text
            print(hs_code)
            # 결정 세번이 여러개인 경우
            if len(hs_code) > 1:
                n = len(hs_code)
                hs_code_list.append(hs_code.split(' ')[1:n:2]) 
            else:
                hs_code_list.append(hs_code.split(' ')[0])
            product_list.append(driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[5]/td').text)
            pd_description_list.append(driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[6]/td').text)
            hs_description_list.append(driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[7]/td').text)
                   
    if count == 1: 
        driver.find_element(By.XPATH, '//*[@id="ULS0203042S_T3_container"]/div[2]/ul[3]/li[1]/a').click()
        time.sleep(TIME)
    if count == 0:
        driver.find_element(By.XPATH, '//*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]/a').click()
        time.sleep(TIME)
        count += 1       
                  
# print(count(hs_code_list))
print(len(hs_code_list))

# 1 페이지 3번 //*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[3]/a 
# 2 페이지 3번 //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[3]/a
# 3 페이지 3번 //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[3]/a

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="ULS0203042S_T3_table1"]/tbody/tr[6]/td[4]/a"}
  (Session info: chrome=134.0.6998.118); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7E2ED4C25+3179557]
	(No symbol) [0x00007FF7E2B388A0]
	(No symbol) [0x00007FF7E29C91CA]
	(No symbol) [0x00007FF7E2A1FA67]
	(No symbol) [0x00007FF7E2A1FC9C]
	(No symbol) [0x00007FF7E2A73627]
	(No symbol) [0x00007FF7E2A47C6F]
	(No symbol) [0x00007FF7E2A702F3]
	(No symbol) [0x00007FF7E2A47A03]
	(No symbol) [0x00007FF7E2A106D0]
	(No symbol) [0x00007FF7E2A11983]
	GetHandleVerifier [0x00007FF7E2F367CD+3579853]
	GetHandleVerifier [0x00007FF7E2F4D1D2+3672530]
	GetHandleVerifier [0x00007FF7E2F42153+3627347]
	GetHandleVerifier [0x00007FF7E2CA092A+868650]
	(No symbol) [0x00007FF7E2B42FFF]
	(No symbol) [0x00007FF7E2B3F4A4]
	(No symbol) [0x00007FF7E2B3F646]
	(No symbol) [0x00007FF7E2B2EAA9]
	BaseThreadInitThunk [0x00007FFDB7F8259D+29]
	RtlUserThreadStart [0x00007FFDB8B2AF38+40]

In [30]:
# # 52 페이지에서 멈춤 
# print(len(hs_code_list)) 
# # 785개 중 510개 
# print(hs_code_list[93]) ## hs_code가 여러개인 것은 숫자만 추출된다. 
# print(hs_code_list[1]) ## hs_code가 여러개인 것은 숫자만 추출된다.

785
①
3302.90-0000

In [31]:
# # 리스트 딕셔너리 형태로 저장
# hs_code_samples = {
#     "date" = date_list,     # 시행 일자 
#     "agency" = agency_list,   # 시행 기관 
#     "hs_code" = hs_code_list,  # hs code  
#     "product" = product_list,  # 품명 
#     "pd_description" = pd_description_list,   # 물품 설명 
#     "hs_description" = hs_description_list   # 결정 사유
# }

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (568387237.py, line 3)

In [32]:
# 데이터 프레임에 저장
hs_code_samples = {} 
hs_code_samples['date'] = date_list
hs_code_samples['agency'] = agency_list
hs_code_samples['hs_code'] = hs_code_list
hs_code_samples['product'] = product_list
hs_code_samples['pd_description'] = pd_description_list
hs_code_samples['hs_description'] = hs_description_list

In [33]:
# 데이터 파일에 저장
with open('./datasets/hs_code_samples.txt','w',encoding='utf-8') as f:
    f.write(date_list)
f.close()
print('End')

TypeError: write() argument must be str, not dict

In [111]:
# 데이터 프레임 변환
import pandas as pd          

df = pd.DataFrame(hs_code_samples)
display(df.head())

ValueError: All arrays must be of the same length

In [37]:
# 전처리하기 전 자료 저장 
df.to_csv("hs_code_samples.csv", index=False)

### 저장한 데이터 불러오기

In [17]:
import pandas as pd  

df = pd.read_csv("hs_code_samples.csv")
df.head(1) 
# columns = df.keys().tolist()

,date,agency,hs_code,product,pd_description,hs_description
0,2025-02-07,관세평가분류원,3302.90-0000,Mixture with a basis of odoriferous substances...,"방향성물질(계피 정유 5%, 오레가노 정유 1%), 메도우스위트 추출물 5%, 마늘...",- 관세율표 제33류 주 제2호에 “제3302호에서 “방향성(芳香性) 물질”이란 제...

In [21]:
def preprocess_text(text):
    # 문자열이 아닐 경우, 문자열로 변환하거나 빈 문자열로 처리
    if not isinstance(text, str):
        text = str(text)  # 또는 text = ""
    
    # 특수기호 제거
    text = re.sub(r'[※ㅇ\-•●◆▶★]', '', text)

    # 한자 제거
    text = re.sub(r'\(([\u4E00-\u9FFF]{1,10})\)', '', text)

    # 여러 줄을 한 문장 단위로 정리
    lines = text.strip().splitlines()
    lines = [line.strip() for line in lines if line.strip()]  # 공백 제거 + 빈 줄 제거

    # 문장 내 연속 공백 제거
    lines = [re.sub(r'\s+', ' ', line) for line in lines]

    # 리스트를 하나의 문자열로 합치기 (여기서는 공백을 구분자로 사용)
    return " ".join(lines)

In [60]:
# # 텍스트 전처리 함수 - 리스트로 저장된다 ㅜ
# import re

# def preprocess_text(text):
#     # 특수기호 제거
#     text = re.sub(r'[※ㅇ\-•●◆▶★]', '', text)

#     # 한자 제거
#     text = re.sub(r'\(([\u4E00-\u9FFF]{1,10})\)', '', text)

#     # 여러 줄을 한 문장 단위로 정리
#     lines = text.strip().splitlines()
#     lines = [line.strip() for line in lines if line.strip()]  # 공백 제거 + 빈 줄 제거

#     # 문장 내 연속 공백 제거
#     lines = [re.sub(r'\s+', ' ', line) for line in lines]

#     return lines

In [22]:
# 문자 제거 후 자료 저장  

columns = df.columns

for col in columns:
    df[col] = df[col].apply(preprocess_text)

display(df.head(1))

# # Error - i[n] 변수명이 str이어서 오류가 뜬다. 
# for i in columns:
#     # print()
#     for n, line in enumerate(i):
#         # print(columns)
#         pre_line = preprocess_text(line)
#         i[n] = append(pre_line)  

#     print(len(i))
#     print(i[0]

,date,agency,hs_code,product,pd_description,hs_description
0,20250207,관세평가분류원,3302.900000,Mixture with a basis of odoriferous substances...,"방향성물질(계피 정유 5%, 오레가노 정유 1%), 메도우스위트 추출물 5%, 마늘...",관세율표 제33류 주 제2호에 “제3302호에서 “방향성 물질”이란 제3301호의 ...

In [106]:
df.head()

,date,agency,hs_code,product,pd_description,hs_description
0,[20250207],[관세평가분류원],[3302.900000],Mixture with a basis of odoriferous substances...,"방향성물질(계피 정유 5%, 오레가노 정유 1%), 메도우스위트 추출물 5%, 마늘...",- 관세율표 제33류 주 제2호에 “제3302호에서 “방향성(芳香性) 물질”이란 제...
1,[20250207],[관세평가분류원],[3302.900000],Mixture with a basis of odoriferous substances...,"방향성물질(Eucalyptol 1.79%, Menthol 0.99%), 비타민 E ...",- 관세율표 제33류 주 제2호에 “제3302호에서 “방향성(芳香性) 물질”이란 제...
2,[20241010],[관세평가분류원],[3306.902000],산부식제; E-5502EBM; 5g ea/Syringes; US;,"ㅇ 인산, 벤잘코늄클로라이드, 잔탄검, 색소, 증류수 등으로 혼합·조제된 청색 겔상...",ㅇ 관세율표 제3306호에는 “구강ㆍ치과 위생용 제품류[치열 교정용 페이스트(pas...
3,[20241010],[관세평가분류원],[3302.101000],Mixture with a basis of odoriferous substances...,"방향성 물질 10.4%(Acetoin 8%, Acetaldehyde 1%, 2,3-...",ㅇ 관세율표 제3302호에는 “방향성(芳香性) 물질의 혼합물과 방향성(芳香性) 물질...
4,[20240704],[관세평가분류원],[3302.900000],Mixtures with a basis of odoriferous substance...,"- 방향성 물질(Oregano essential oil, Garlic essenti...",ㅇ 관세율표 제3302호에 “방향성(芳香性) 물질의 혼합물과 방향성(芳香性) 물질의...

In [103]:
# 전처리 후 자료 저장
df.to_csv("pre_hs_code_samples.csv", index=False)

### 실험

In [7]:
# 컬럼명을 변수로, 값은 리스트로 저장 ! 



for col in columns:
    globals()[col] = df[col].tolist()

print(date[0:5])
df.head(1) 
# print(df.keys().tolist())
# for col, val in df.items():            
#     col = []                            
#     col = val.tolist()                  
#     print(col[0])

['2025-02-07', '2025-02-07', '2024-10-10', '2024-10-10', '2024-07-04']

,date,agency,hs_code,product,pd_description,hs_description
0,2025-02-07,관세평가분류원,3302.90-0000,Mixture with a basis of odoriferous substances...,"방향성물질(계피 정유 5%, 오레가노 정유 1%), 메도우스위트 추출물 5%, 마늘...",- 관세율표 제33류 주 제2호에 “제3302호에서 “방향성(芳香性) 물질”이란 제...

In [52]:
date_list = [] 
driver.find_element(By.XPATH, f'//*[@id="ULS0203042S_T3_table1"]/tbody/tr[1]/td[4]/a').click()
time.sleep(TIME)

date_list.append(driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[2]/td').text)

print(date_list)

['2025-02-07']

In [40]:
# soup = BeautifulSoup(driver.page_source, 'lxml')

# CSS_SELECTOR 는 에러 -> XPATH로 변환 
# driver.find_element(By.CSS_SELECTOR, '#ULS0203042S_T3_table1 > tbody > tr.selectedon > td.ellipsis.hlzone2 > a').click()
# 사례 1 페이지 CSS_SELECTOR
#ULS0203042S_T3_table1 > tbody > tr.selectedon > td.ellipsis.hlzone2 > a
#ULS0203042S_T3_table1 > tbody > tr:nth-child(2) > td.ellipsis.hlzone2 > a
#ULS0203042S_T3_table1 > tbody > tr:nth-child(10) > td.ellipsis.hlzone2 > a

# 2 페이지 1 
#ULS0203042S_T3_table1 > tbody > tr:nth-child(1) > td.ellipsis.hlzone2 > a

# 첫번째 사례 
driver.find_element(By.XPATH, f'//*[@id="ULS0203042S_T3_table1"]/tbody/tr[1]/td[4]/a').click()

# case = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody').text
date = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[2]/td').text
agency = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[3]/td').text
hs_code = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[4]/td').text.split(' ')[0]
product = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[5]/td').text
pd_description = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[6]/td').text
hs_description = driver.find_element(By.XPATH, f'//*[@id="ULS0203037S_T1_table1"]/tbody/tr[7]/td').text
# 독립변수 활용 가능성 

# print(date) ## 2024-04-16
# print(case)
print(agency) ## 관세평가분류원 
print(hs_code) ## 3302.90-0000
print(product) # 영문명
print(pd_description)
print(hs_description)
# for i in range(1,11): 
        



# 2페이지 
driver.find_element(By.XPATH, '//*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[2]').click()
time.sleep(TIME)

# driver.find_element(By.XPATH, '//*[@id="ULS0203042S_T3_table1"]/tbody/tr[1]/td[4]/a').click()
# time.sleep(TIME)
# 다음 페이지
driver.find_element(By.XPATH, '//*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]/a').click()

# driver.find_element(By.XPATH, f'').click()
# driver.find_element(By.XPATH, f'').text


# 사례
# //*[@id="ULS0203042S_T3_table1"]/tbody/tr[2]/td[4]/a


# 1페이지
# //*[@id="ULS0203042S_T3_table1"]/tbody/tr[1]/td[4]/a
# //*[@id="ULS0203042S_T3_table1"]/tbody/tr[2]/td[4]/a
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[10]/a

# 2페이지 
# 1번
# //*[@id="ULS0203042S_T3_table1"]/tbody/tr[1]/td[4]/a
# 11번 버튼
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]


# 다음 페이지 버튼
# 1~10
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]/a
# 11~20
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[3]/li[1]/a
# 21~30
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[3]/li[1]/a
# 31~40
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[3]/li[1]/a

# 제일 마지막 페이지의 이전 페이지 버튼 
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[2]/a

# 2페이지 버튼 
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[2]
# 3페이지 버튼
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[3]/a
# 11페이지 버튼 
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]
# 12페이지 버튼 
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[2]/a

# 사례 텍스트 
# //*[@id="ULS0203037S_T1_table1"]/tbody/tr[2]/td
# //*[@id="ULS0203037S_T1_table1"]/tbody/tr[3]/td
# //*[@id="ULS0203037S_T1_table1"]/tbody/tr[4]/td # 결정 세번 


# driver.find_element(By.XPATH, '//*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]/a').click()

# driver.find_element(By.XPATH, f'//*[@id="ULS0203042S_T3_container"]/div[2]/ul[1]/li[1]').click()

# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[2]/li[1]
# //*[@id="ULS0203042S_T3_table1"]/tbody/tr[1]/td[4]/a

# # 
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[3]/li[1]/a
# //*[@id="ULS0203042S_T3_container"]/div[2]/ul[3]/li[2]/a

관세평가분류원
3302.90-0000
Mixtures with a basis of odoriferous substance; PAN-TEK VANILLA FRUITY TM
- 방향성 물질[Ethyl vanillin, gamma-Undecalactone, Butyric acid, Linalool, Diacetyl, 4-Hydroxy-2,5-dimethyl-3(2H)-furanone] 20.87%에 Silica, Propylene glycol을 혼합한 미황색계 분말상

- 용도 : 사료용

※ 품목분류는 수출입신고 당시의 물품 상태에 따라 변경될 수 있음.
ㅇ 관세율표 제3302호에 “방향성(芳香性) 물질의 혼합물과 방향성(芳香性) 물질의 하나 이상을 기본 재료로 한 혼합물(알코올의 용액을 포함하며, 공업용 원료로 사용하는 것으로 한정한다), 방향성(芳香性) 물질을 기본 재료로 한 그 밖의 조제품(음료제조용으로 한정한다)”이 분류되며,

- 같은 호 HS해설서에서 “이 호에는 하나 이상의 방향성물질(정유·레지노이드·추출한 올레오수지 또는 합성향료)에 희석제·증량제(carriers)(예: 식물유·덱스트로스 또는 전분)를 첨가하여 화합된 혼합물이 분류된다.”라고 설명하고 있음

ㅇ 따라서, 본 물품은 하나 이상의 방향성 물질을 기본 재료로 한 혼합물에 해당하므로 관세율표의 해석에 관한 통칙 제1호와 제6호에 따라 제3302.90-0000호에 분류함

In [38]:
preprocess_text(description)

['방향성 물질[Ethyl vanillin, gammaUndecalactone, Butyric acid, Linalool, Diacetyl, 4Hydroxy2,5dimethyl3furanone] 20.87%에 Silica, Propylene glycol을 혼합한 미황색계 분말상',
 '용도 : 사료용',
 '품목분류는 수출입신고 당시의 물품 상태에 따라 변경될 수 있음.']

### 출력 후 전처리

In [18]:


df["hs_code_numeric"] = df["hs_code"].astype(str).apply(lambda x: re.sub(r'[^0-9]', '', x))

NameError: name 'df' is not defined